### ISSUE TITLE
Task doesn't finish

### ISSUE THREAD

**Issue by zakjan** [MeirionHughes/gulp-aurelia-template-lint#4]
I tried to activate `useStaticTyping = true` but gulp tasks now just hangs up for me. No other tasks are started. Exit code 0. Version 0.7.2

```
$ gulp watch
[15:22:06] Using gulpfile xxx/gulpfile.js
[15:22:06] Starting 'build'...
[15:22:06] Starting 'lint-html'...
```

There is nothing more. Is there some verbose output I could activate?

My gulp config:

```
var gulp = require('gulp');
var aureliaTemplateLint = require('gulp-aurelia-template-lint');
var aureliaTemplateLintConfig = new (require('aurelia-template-lint').Config);
var paths = require('../paths');

aureliaTemplateLintConfig.useStaticTyping = true;

gulp.task('lint-html', function () {
    return gulp.src(paths.html)
        .pipe(aureliaTemplateLint(aureliaTemplateLintConfig));
});
```

**Comment by MeirionHughes** [comment]
could please you try
```
aureliaTemplateLintConfig.throwStaticTypingErrors = true
```

also you will need to supply the globbing path too: 

aureliaTemplateLintConfig.sourceFileGlob = "source/**/*.ts"

unfortunatly, at the moment your view's and viewModels will have to be side-by-side. I need to work on a way to allow different folders.

**Comment by MeirionHughes** [comment]
btw, this has already been updated to Aurelia RC and I think it will fall over if you don't upgrade the entire project too.

**Comment by MeirionHughes** [comment]
one more thing to try; clone this repository, `npm install`, `gulp test-example`. that should run the gulp plug-in on the example; if that doesn't work it might be a versioning thing elsewhere.

**Comment by zakjan** [comment]
Yeah, I've already upgraded to Aurelia RC too.

Setting sourceFileGlob helped for me. I haven't noticed the readme chapter documenting this new feature. Thanks a lot for your awesome work!

**Comment by MeirionHughes** [comment]
Cool! It will get better, slowly making my way through the bugs. :beetle:
